/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  NFTfiSigningUtils,
  NFTfiSigningUtilsInterface,
} from "../../../../contracts/nftfi/v1/NFTfiSigningUtils";

const _abi = [
  {
    inputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    constant: true,
    inputs: [],
    name: "getChainID",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        internalType: "uint256",
        name: "_nftCollateralId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_borrowerNonce",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_nftCollateralContract",
        type: "address",
      },
      {
        internalType: "address",
        name: "_borrower",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_borrowerSignature",
        type: "bytes",
      },
    ],
    name: "isValidBorrowerSignature",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        internalType: "uint256",
        name: "_loanPrincipalAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_maximumRepaymentAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_nftCollateralId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_loanDuration",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_loanInterestRateForDurationInBasisPoints",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_adminFeeInBasisPoints",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_lenderNonce",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_nftCollateralContract",
        type: "address",
      },
      {
        internalType: "address",
        name: "_loanERC20Denomination",
        type: "address",
      },
      {
        internalType: "address",
        name: "_lender",
        type: "address",
      },
      {
        internalType: "bool",
        name: "_interestIsProRated",
        type: "bool",
      },
      {
        internalType: "bytes",
        name: "_lenderSignature",
        type: "bytes",
      },
    ],
    name: "isValidLenderSignature",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
] as const;

export class NFTfiSigningUtils__factory {
  static readonly abi = _abi;
  static createInterface(): NFTfiSigningUtilsInterface {
    return new utils.Interface(_abi) as NFTfiSigningUtilsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): NFTfiSigningUtils {
    return new Contract(address, _abi, signerOrProvider) as NFTfiSigningUtils;
  }
}
