/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IEssenceNFTEvents,
  IEssenceNFTEventsInterface,
} from "../../../../contracts/cyberconnect/interfaces/IEssenceNFTEvents";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "profileId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "essenceId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "name",
        type: "string",
      },
      {
        indexed: false,
        internalType: "string",
        name: "symbol",
        type: "string",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "transferable",
        type: "bool",
      },
    ],
    name: "Initialize",
    type: "event",
  },
] as const;

export class IEssenceNFTEvents__factory {
  static readonly abi = _abi;
  static createInterface(): IEssenceNFTEventsInterface {
    return new utils.Interface(_abi) as IEssenceNFTEventsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IEssenceNFTEvents {
    return new Contract(address, _abi, signerOrProvider) as IEssenceNFTEvents;
  }
}
