/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IProfileMiddleware,
  IProfileMiddlewareInterface,
} from "../../../../contracts/cyberconnect/interfaces/IProfileMiddleware";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "to",
            type: "address",
          },
          {
            internalType: "string",
            name: "handle",
            type: "string",
          },
          {
            internalType: "string",
            name: "avatar",
            type: "string",
          },
          {
            internalType: "string",
            name: "metadata",
            type: "string",
          },
          {
            internalType: "address",
            name: "operator",
            type: "address",
          },
        ],
        internalType: "struct DataTypes.CreateProfileParams",
        name: "params",
        type: "tuple",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "postProcess",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "to",
            type: "address",
          },
          {
            internalType: "string",
            name: "handle",
            type: "string",
          },
          {
            internalType: "string",
            name: "avatar",
            type: "string",
          },
          {
            internalType: "string",
            name: "metadata",
            type: "string",
          },
          {
            internalType: "address",
            name: "operator",
            type: "address",
          },
        ],
        internalType: "struct DataTypes.CreateProfileParams",
        name: "params",
        type: "tuple",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "preProcess",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "namespace",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "setProfileMwData",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IProfileMiddleware__factory {
  static readonly abi = _abi;
  static createInterface(): IProfileMiddlewareInterface {
    return new utils.Interface(_abi) as IProfileMiddlewareInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IProfileMiddleware {
    return new Contract(address, _abi, signerOrProvider) as IProfileMiddleware;
  }
}
