/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IProfileDeployer,
  IProfileDeployerInterface,
} from "../../../../contracts/cyberconnect/interfaces/IProfileDeployer";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "salt",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "engine",
        type: "address",
      },
      {
        internalType: "address",
        name: "subscribeBeacon",
        type: "address",
      },
      {
        internalType: "address",
        name: "essenceBeacon",
        type: "address",
      },
    ],
    name: "deployProfile",
    outputs: [
      {
        internalType: "address",
        name: "addr",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "profileParams",
    outputs: [
      {
        internalType: "address",
        name: "engine",
        type: "address",
      },
      {
        internalType: "address",
        name: "subBeacon",
        type: "address",
      },
      {
        internalType: "address",
        name: "essenceBeacon",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IProfileDeployer__factory {
  static readonly abi = _abi;
  static createInterface(): IProfileDeployerInterface {
    return new utils.Interface(_abi) as IProfileDeployerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IProfileDeployer {
    return new Contract(address, _abi, signerOrProvider) as IProfileDeployer;
  }
}
