/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IProfileNFTDescriptorV2,
  IProfileNFTDescriptorV2Interface,
} from "../../../../contracts/cyberconnect/interfaces/IProfileNFTDescriptorV2";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "tokenId",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "handle",
            type: "string",
          },
          {
            internalType: "uint256",
            name: "subscribers",
            type: "uint256",
          },
        ],
        internalType: "struct DataTypes.ConstructTokenURIParams",
        name: "params",
        type: "tuple",
      },
    ],
    name: "tokenURI",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IProfileNFTDescriptorV2__factory {
  static readonly abi = _abi;
  static createInterface(): IProfileNFTDescriptorV2Interface {
    return new utils.Interface(_abi) as IProfileNFTDescriptorV2Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IProfileNFTDescriptorV2 {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IProfileNFTDescriptorV2;
  }
}
