/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as nfTfiSol from "./NFTfi.sol";
export type { nfTfiSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as openzeppelin from "./openzeppelin";
export type { openzeppelin };
export type { NFTfiAdmin } from "./NFTfiAdmin";
export type { NFTfiSigningUtils } from "./NFTfiSigningUtils";
