/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export declare namespace DataTypes {
  export type ConstructTokenURIParamsStruct = {
    tokenId: PromiseOrValue<BigNumberish>;
    handle: PromiseOrValue<string>;
    subscribers: PromiseOrValue<BigNumberish>;
  };

  export type ConstructTokenURIParamsStructOutput = [
    BigNumber,
    string,
    BigNumber
  ] & { tokenId: BigNumber; handle: string; subscribers: BigNumber };
}

export interface IProfileNFTDescriptorInterface extends utils.Interface {
  functions: {
    "setAnimationTemplate(string)": FunctionFragment;
    "tokenURI((uint256,string,uint256))": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "setAnimationTemplate" | "tokenURI"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "setAnimationTemplate",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [DataTypes.ConstructTokenURIParamsStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "setAnimationTemplate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;

  events: {};
}

export interface IProfileNFTDescriptor extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IProfileNFTDescriptorInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    setAnimationTemplate(
      template: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    tokenURI(
      params: DataTypes.ConstructTokenURIParamsStruct,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  setAnimationTemplate(
    template: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  tokenURI(
    params: DataTypes.ConstructTokenURIParamsStruct,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    setAnimationTemplate(
      template: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    tokenURI(
      params: DataTypes.ConstructTokenURIParamsStruct,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    setAnimationTemplate(
      template: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    tokenURI(
      params: DataTypes.ConstructTokenURIParamsStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    setAnimationTemplate(
      template: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    tokenURI(
      params: DataTypes.ConstructTokenURIParamsStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
