/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface IProfileDeployerInterface extends utils.Interface {
  functions: {
    "deployProfile(bytes32,address,address,address)": FunctionFragment;
    "profileParams()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "deployProfile" | "profileParams"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "deployProfile",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "profileParams",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "deployProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "profileParams",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IProfileDeployer extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IProfileDeployerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    deployProfile(
      salt: PromiseOrValue<BytesLike>,
      engine: PromiseOrValue<string>,
      subscribeBeacon: PromiseOrValue<string>,
      essenceBeacon: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    profileParams(
      overrides?: CallOverrides
    ): Promise<
      [string, string, string] & {
        engine: string;
        subBeacon: string;
        essenceBeacon: string;
      }
    >;
  };

  deployProfile(
    salt: PromiseOrValue<BytesLike>,
    engine: PromiseOrValue<string>,
    subscribeBeacon: PromiseOrValue<string>,
    essenceBeacon: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  profileParams(
    overrides?: CallOverrides
  ): Promise<
    [string, string, string] & {
      engine: string;
      subBeacon: string;
      essenceBeacon: string;
    }
  >;

  callStatic: {
    deployProfile(
      salt: PromiseOrValue<BytesLike>,
      engine: PromiseOrValue<string>,
      subscribeBeacon: PromiseOrValue<string>,
      essenceBeacon: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    profileParams(
      overrides?: CallOverrides
    ): Promise<
      [string, string, string] & {
        engine: string;
        subBeacon: string;
        essenceBeacon: string;
      }
    >;
  };

  filters: {};

  estimateGas: {
    deployProfile(
      salt: PromiseOrValue<BytesLike>,
      engine: PromiseOrValue<string>,
      subscribeBeacon: PromiseOrValue<string>,
      essenceBeacon: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    profileParams(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    deployProfile(
      salt: PromiseOrValue<BytesLike>,
      engine: PromiseOrValue<string>,
      subscribeBeacon: PromiseOrValue<string>,
      essenceBeacon: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    profileParams(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
