/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface ISubscribeDeployerInterface extends utils.Interface {
  functions: {
    "deploySubscribe(bytes32,address)": FunctionFragment;
    "subParams()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "deploySubscribe" | "subParams"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "deploySubscribe",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "subParams", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "deploySubscribe",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "subParams", data: BytesLike): Result;

  events: {};
}

export interface ISubscribeDeployer extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ISubscribeDeployerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    deploySubscribe(
      salt: PromiseOrValue<BytesLike>,
      profileProxy: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    subParams(
      overrides?: CallOverrides
    ): Promise<[string] & { profileProxy: string }>;
  };

  deploySubscribe(
    salt: PromiseOrValue<BytesLike>,
    profileProxy: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  subParams(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    deploySubscribe(
      salt: PromiseOrValue<BytesLike>,
      profileProxy: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    subParams(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    deploySubscribe(
      salt: PromiseOrValue<BytesLike>,
      profileProxy: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    subParams(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    deploySubscribe(
      salt: PromiseOrValue<BytesLike>,
      profileProxy: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    subParams(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
