/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as infTfiSigningUtilsSol from "./INFTfiSigningUtils.sol";
export type { infTfiSigningUtilsSol };
export type { INFTfi } from "./INFTfi";
export type { INFTfiAdmin } from "./INFTfiAdmin";
export type { IOwnable } from "./IOwnable";
