/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../common";

export interface NFTfiInterface extends utils.Interface {
  functions: {
    "addPauser(address)": FunctionFragment;
    "adminFeeInBasisPoints()": FunctionFragment;
    "approve(address,uint256)": FunctionFragment;
    "balanceOf(address)": FunctionFragment;
    "beginLoan(uint256,uint256,uint256,uint256,uint256,uint256,uint256[2],address,address,address,bytes,bytes)": FunctionFragment;
    "cancelLoanCommitmentBeforeLoanHasBegun(uint256)": FunctionFragment;
    "erc20CurrencyIsWhitelisted(address)": FunctionFragment;
    "getApproved(uint256)": FunctionFragment;
    "getChainID()": FunctionFragment;
    "getPayoffAmount(uint256)": FunctionFragment;
    "getWhetherNonceHasBeenUsedForUser(address,uint256)": FunctionFragment;
    "isApprovedForAll(address,address)": FunctionFragment;
    "isOwner()": FunctionFragment;
    "isPauser(address)": FunctionFragment;
    "isValidBorrowerSignature(uint256,uint256,address,address,bytes)": FunctionFragment;
    "isValidLenderSignature(uint256,uint256,uint256,uint256,uint256,uint256,uint256,address,address,address,bool,bytes)": FunctionFragment;
    "liquidateOverdueLoan(uint256)": FunctionFragment;
    "loanIdToLoan(uint256)": FunctionFragment;
    "loanRepaidOrLiquidated(uint256)": FunctionFragment;
    "maximumLoanDuration()": FunctionFragment;
    "maximumNumberOfActiveLoans()": FunctionFragment;
    "name()": FunctionFragment;
    "nftContractIsWhitelisted(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "ownerOf(uint256)": FunctionFragment;
    "pause()": FunctionFragment;
    "paused()": FunctionFragment;
    "payBackLoan(uint256)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "renouncePauser()": FunctionFragment;
    "safeTransferFrom(address,address,uint256)": FunctionFragment;
    "safeTransferFrom(address,address,uint256,bytes)": FunctionFragment;
    "setApprovalForAll(address,bool)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "symbol()": FunctionFragment;
    "totalActiveLoans()": FunctionFragment;
    "totalNumLoans()": FunctionFragment;
    "transferFrom(address,address,uint256)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "unpause()": FunctionFragment;
    "updateAdminFee(uint256)": FunctionFragment;
    "updateMaximumLoanDuration(uint256)": FunctionFragment;
    "updateMaximumNumberOfActiveLoans(uint256)": FunctionFragment;
    "whitelistERC20Currency(address,bool)": FunctionFragment;
    "whitelistNFTContract(address,bool)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addPauser"
      | "adminFeeInBasisPoints"
      | "approve"
      | "balanceOf"
      | "beginLoan"
      | "cancelLoanCommitmentBeforeLoanHasBegun"
      | "erc20CurrencyIsWhitelisted"
      | "getApproved"
      | "getChainID"
      | "getPayoffAmount"
      | "getWhetherNonceHasBeenUsedForUser"
      | "isApprovedForAll"
      | "isOwner"
      | "isPauser"
      | "isValidBorrowerSignature"
      | "isValidLenderSignature"
      | "liquidateOverdueLoan"
      | "loanIdToLoan"
      | "loanRepaidOrLiquidated"
      | "maximumLoanDuration"
      | "maximumNumberOfActiveLoans"
      | "name"
      | "nftContractIsWhitelisted"
      | "owner"
      | "ownerOf"
      | "pause"
      | "paused"
      | "payBackLoan"
      | "renounceOwnership"
      | "renouncePauser"
      | "safeTransferFrom(address,address,uint256)"
      | "safeTransferFrom(address,address,uint256,bytes)"
      | "setApprovalForAll"
      | "supportsInterface"
      | "symbol"
      | "totalActiveLoans"
      | "totalNumLoans"
      | "transferFrom"
      | "transferOwnership"
      | "unpause"
      | "updateAdminFee"
      | "updateMaximumLoanDuration"
      | "updateMaximumNumberOfActiveLoans"
      | "whitelistERC20Currency"
      | "whitelistNFTContract"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addPauser",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "adminFeeInBasisPoints",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "beginLoan",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>],
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelLoanCommitmentBeforeLoanHasBegun",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "erc20CurrencyIsWhitelisted",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getApproved",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getChainID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPayoffAmount",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getWhetherNonceHasBeenUsedForUser",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "isOwner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isPauser",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidBorrowerSignature",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidLenderSignature",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<boolean>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidateOverdueLoan",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "loanIdToLoan",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "loanRepaidOrLiquidated",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "maximumLoanDuration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maximumNumberOfActiveLoans",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "nftContractIsWhitelisted",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payBackLoan",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renouncePauser",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [PromiseOrValue<string>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalActiveLoans",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalNumLoans",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateAdminFee",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMaximumLoanDuration",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMaximumNumberOfActiveLoans",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistERC20Currency",
    values: [PromiseOrValue<string>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistNFTContract",
    values: [PromiseOrValue<string>, PromiseOrValue<boolean>]
  ): string;

  decodeFunctionResult(functionFragment: "addPauser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "adminFeeInBasisPoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "beginLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelLoanCommitmentBeforeLoanHasBegun",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "erc20CurrencyIsWhitelisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getChainID", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPayoffAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWhetherNonceHasBeenUsedForUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isOwner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isPauser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isValidBorrowerSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidLenderSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidateOverdueLoan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "loanIdToLoan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "loanRepaidOrLiquidated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maximumLoanDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maximumNumberOfActiveLoans",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nftContractIsWhitelisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "payBackLoan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renouncePauser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom(address,address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalActiveLoans",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalNumLoans",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateAdminFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMaximumLoanDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMaximumNumberOfActiveLoans",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistERC20Currency",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistNFTContract",
    data: BytesLike
  ): Result;

  events: {
    "AdminFeeUpdated(uint256)": EventFragment;
    "Approval(address,address,uint256)": EventFragment;
    "ApprovalForAll(address,address,bool)": EventFragment;
    "LoanLiquidated(uint256,address,address,uint256,uint256,uint256,uint256,address)": EventFragment;
    "LoanRepaid(uint256,address,address,uint256,uint256,uint256,uint256,address,address)": EventFragment;
    "LoanStarted(uint256,address,address,uint256,uint256,uint256,uint256,uint256,uint256,address,address,bool)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "Paused(address)": EventFragment;
    "PauserAdded(address)": EventFragment;
    "PauserRemoved(address)": EventFragment;
    "Transfer(address,address,uint256)": EventFragment;
    "Unpaused(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AdminFeeUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Approval"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ApprovalForAll"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LoanLiquidated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LoanRepaid"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LoanStarted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PauserAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PauserRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Transfer"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
}

export interface AdminFeeUpdatedEventObject {
  newAdminFee: BigNumber;
}
export type AdminFeeUpdatedEvent = TypedEvent<
  [BigNumber],
  AdminFeeUpdatedEventObject
>;

export type AdminFeeUpdatedEventFilter = TypedEventFilter<AdminFeeUpdatedEvent>;

export interface ApprovalEventObject {
  owner: string;
  approved: string;
  tokenId: BigNumber;
}
export type ApprovalEvent = TypedEvent<
  [string, string, BigNumber],
  ApprovalEventObject
>;

export type ApprovalEventFilter = TypedEventFilter<ApprovalEvent>;

export interface ApprovalForAllEventObject {
  owner: string;
  operator: string;
  approved: boolean;
}
export type ApprovalForAllEvent = TypedEvent<
  [string, string, boolean],
  ApprovalForAllEventObject
>;

export type ApprovalForAllEventFilter = TypedEventFilter<ApprovalForAllEvent>;

export interface LoanLiquidatedEventObject {
  loanId: BigNumber;
  borrower: string;
  lender: string;
  loanPrincipalAmount: BigNumber;
  nftCollateralId: BigNumber;
  loanMaturityDate: BigNumber;
  loanLiquidationDate: BigNumber;
  nftCollateralContract: string;
}
export type LoanLiquidatedEvent = TypedEvent<
  [
    BigNumber,
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    string
  ],
  LoanLiquidatedEventObject
>;

export type LoanLiquidatedEventFilter = TypedEventFilter<LoanLiquidatedEvent>;

export interface LoanRepaidEventObject {
  loanId: BigNumber;
  borrower: string;
  lender: string;
  loanPrincipalAmount: BigNumber;
  nftCollateralId: BigNumber;
  amountPaidToLender: BigNumber;
  adminFee: BigNumber;
  nftCollateralContract: string;
  loanERC20Denomination: string;
}
export type LoanRepaidEvent = TypedEvent<
  [
    BigNumber,
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    string,
    string
  ],
  LoanRepaidEventObject
>;

export type LoanRepaidEventFilter = TypedEventFilter<LoanRepaidEvent>;

export interface LoanStartedEventObject {
  loanId: BigNumber;
  borrower: string;
  lender: string;
  loanPrincipalAmount: BigNumber;
  maximumRepaymentAmount: BigNumber;
  nftCollateralId: BigNumber;
  loanStartTime: BigNumber;
  loanDuration: BigNumber;
  loanInterestRateForDurationInBasisPoints: BigNumber;
  nftCollateralContract: string;
  loanERC20Denomination: string;
  interestIsProRated: boolean;
}
export type LoanStartedEvent = TypedEvent<
  [
    BigNumber,
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    string,
    string,
    boolean
  ],
  LoanStartedEventObject
>;

export type LoanStartedEventFilter = TypedEventFilter<LoanStartedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface PausedEventObject {
  account: string;
}
export type PausedEvent = TypedEvent<[string], PausedEventObject>;

export type PausedEventFilter = TypedEventFilter<PausedEvent>;

export interface PauserAddedEventObject {
  account: string;
}
export type PauserAddedEvent = TypedEvent<[string], PauserAddedEventObject>;

export type PauserAddedEventFilter = TypedEventFilter<PauserAddedEvent>;

export interface PauserRemovedEventObject {
  account: string;
}
export type PauserRemovedEvent = TypedEvent<[string], PauserRemovedEventObject>;

export type PauserRemovedEventFilter = TypedEventFilter<PauserRemovedEvent>;

export interface TransferEventObject {
  from: string;
  to: string;
  tokenId: BigNumber;
}
export type TransferEvent = TypedEvent<
  [string, string, BigNumber],
  TransferEventObject
>;

export type TransferEventFilter = TypedEventFilter<TransferEvent>;

export interface UnpausedEventObject {
  account: string;
}
export type UnpausedEvent = TypedEvent<[string], UnpausedEventObject>;

export type UnpausedEventFilter = TypedEventFilter<UnpausedEvent>;

export interface NFTfi extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: NFTfiInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addPauser(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    adminFeeInBasisPoints(overrides?: CallOverrides): Promise<[BigNumber]>;

    approve(
      to: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    balanceOf(
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    beginLoan(
      _loanPrincipalAmount: PromiseOrValue<BigNumberish>,
      _maximumRepaymentAmount: PromiseOrValue<BigNumberish>,
      _nftCollateralId: PromiseOrValue<BigNumberish>,
      _loanDuration: PromiseOrValue<BigNumberish>,
      _loanInterestRateForDurationInBasisPoints: PromiseOrValue<BigNumberish>,
      _adminFeeInBasisPoints: PromiseOrValue<BigNumberish>,
      _borrowerAndLenderNonces: [
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>
      ],
      _nftCollateralContract: PromiseOrValue<string>,
      _loanERC20Denomination: PromiseOrValue<string>,
      _lender: PromiseOrValue<string>,
      _borrowerSignature: PromiseOrValue<BytesLike>,
      _lenderSignature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    cancelLoanCommitmentBeforeLoanHasBegun(
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    erc20CurrencyIsWhitelisted(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    getApproved(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getChainID(overrides?: CallOverrides): Promise<[BigNumber]>;

    getPayoffAmount(
      _loanId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getWhetherNonceHasBeenUsedForUser(
      _user: PromiseOrValue<string>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isApprovedForAll(
      owner: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isOwner(overrides?: CallOverrides): Promise<[boolean]>;

    isPauser(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isValidBorrowerSignature(
      _nftCollateralId: PromiseOrValue<BigNumberish>,
      _borrowerNonce: PromiseOrValue<BigNumberish>,
      _nftCollateralContract: PromiseOrValue<string>,
      _borrower: PromiseOrValue<string>,
      _borrowerSignature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isValidLenderSignature(
      _loanPrincipalAmount: PromiseOrValue<BigNumberish>,
      _maximumRepaymentAmount: PromiseOrValue<BigNumberish>,
      _nftCollateralId: PromiseOrValue<BigNumberish>,
      _loanDuration: PromiseOrValue<BigNumberish>,
      _loanInterestRateForDurationInBasisPoints: PromiseOrValue<BigNumberish>,
      _adminFeeInBasisPoints: PromiseOrValue<BigNumberish>,
      _lenderNonce: PromiseOrValue<BigNumberish>,
      _nftCollateralContract: PromiseOrValue<string>,
      _loanERC20Denomination: PromiseOrValue<string>,
      _lender: PromiseOrValue<string>,
      _interestIsProRated: PromiseOrValue<boolean>,
      _lenderSignature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    liquidateOverdueLoan(
      _loanId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    loanIdToLoan(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        number,
        number,
        number,
        string,
        string,
        string,
        boolean
      ] & {
        loanId: BigNumber;
        loanPrincipalAmount: BigNumber;
        maximumRepaymentAmount: BigNumber;
        nftCollateralId: BigNumber;
        loanStartTime: BigNumber;
        loanDuration: number;
        loanInterestRateForDurationInBasisPoints: number;
        loanAdminFeeInBasisPoints: number;
        nftCollateralContract: string;
        loanERC20Denomination: string;
        borrower: string;
        interestIsProRated: boolean;
      }
    >;

    loanRepaidOrLiquidated(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    maximumLoanDuration(overrides?: CallOverrides): Promise<[BigNumber]>;

    maximumNumberOfActiveLoans(overrides?: CallOverrides): Promise<[BigNumber]>;

    name(overrides?: CallOverrides): Promise<[string]>;

    nftContractIsWhitelisted(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    ownerOf(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    payBackLoan(
      _loanId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renouncePauser(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "safeTransferFrom(address,address,uint256)"(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "safeTransferFrom(address,address,uint256,bytes)"(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      _data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setApprovalForAll(
      to: PromiseOrValue<string>,
      approved: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    symbol(overrides?: CallOverrides): Promise<[string]>;

    totalActiveLoans(overrides?: CallOverrides): Promise<[BigNumber]>;

    totalNumLoans(overrides?: CallOverrides): Promise<[BigNumber]>;

    transferFrom(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateAdminFee(
      _newAdminFeeInBasisPoints: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateMaximumLoanDuration(
      _newMaximumLoanDuration: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateMaximumNumberOfActiveLoans(
      _newMaximumNumberOfActiveLoans: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    whitelistERC20Currency(
      _erc20Currency: PromiseOrValue<string>,
      _setAsWhitelisted: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    whitelistNFTContract(
      _nftContract: PromiseOrValue<string>,
      _setAsWhitelisted: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  addPauser(
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  adminFeeInBasisPoints(overrides?: CallOverrides): Promise<BigNumber>;

  approve(
    to: PromiseOrValue<string>,
    tokenId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  balanceOf(
    owner: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  beginLoan(
    _loanPrincipalAmount: PromiseOrValue<BigNumberish>,
    _maximumRepaymentAmount: PromiseOrValue<BigNumberish>,
    _nftCollateralId: PromiseOrValue<BigNumberish>,
    _loanDuration: PromiseOrValue<BigNumberish>,
    _loanInterestRateForDurationInBasisPoints: PromiseOrValue<BigNumberish>,
    _adminFeeInBasisPoints: PromiseOrValue<BigNumberish>,
    _borrowerAndLenderNonces: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ],
    _nftCollateralContract: PromiseOrValue<string>,
    _loanERC20Denomination: PromiseOrValue<string>,
    _lender: PromiseOrValue<string>,
    _borrowerSignature: PromiseOrValue<BytesLike>,
    _lenderSignature: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  cancelLoanCommitmentBeforeLoanHasBegun(
    _nonce: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  erc20CurrencyIsWhitelisted(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  getApproved(
    tokenId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getChainID(overrides?: CallOverrides): Promise<BigNumber>;

  getPayoffAmount(
    _loanId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getWhetherNonceHasBeenUsedForUser(
    _user: PromiseOrValue<string>,
    _nonce: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isApprovedForAll(
    owner: PromiseOrValue<string>,
    operator: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isOwner(overrides?: CallOverrides): Promise<boolean>;

  isPauser(
    account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isValidBorrowerSignature(
    _nftCollateralId: PromiseOrValue<BigNumberish>,
    _borrowerNonce: PromiseOrValue<BigNumberish>,
    _nftCollateralContract: PromiseOrValue<string>,
    _borrower: PromiseOrValue<string>,
    _borrowerSignature: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isValidLenderSignature(
    _loanPrincipalAmount: PromiseOrValue<BigNumberish>,
    _maximumRepaymentAmount: PromiseOrValue<BigNumberish>,
    _nftCollateralId: PromiseOrValue<BigNumberish>,
    _loanDuration: PromiseOrValue<BigNumberish>,
    _loanInterestRateForDurationInBasisPoints: PromiseOrValue<BigNumberish>,
    _adminFeeInBasisPoints: PromiseOrValue<BigNumberish>,
    _lenderNonce: PromiseOrValue<BigNumberish>,
    _nftCollateralContract: PromiseOrValue<string>,
    _loanERC20Denomination: PromiseOrValue<string>,
    _lender: PromiseOrValue<string>,
    _interestIsProRated: PromiseOrValue<boolean>,
    _lenderSignature: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  liquidateOverdueLoan(
    _loanId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  loanIdToLoan(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      number,
      number,
      number,
      string,
      string,
      string,
      boolean
    ] & {
      loanId: BigNumber;
      loanPrincipalAmount: BigNumber;
      maximumRepaymentAmount: BigNumber;
      nftCollateralId: BigNumber;
      loanStartTime: BigNumber;
      loanDuration: number;
      loanInterestRateForDurationInBasisPoints: number;
      loanAdminFeeInBasisPoints: number;
      nftCollateralContract: string;
      loanERC20Denomination: string;
      borrower: string;
      interestIsProRated: boolean;
    }
  >;

  loanRepaidOrLiquidated(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  maximumLoanDuration(overrides?: CallOverrides): Promise<BigNumber>;

  maximumNumberOfActiveLoans(overrides?: CallOverrides): Promise<BigNumber>;

  name(overrides?: CallOverrides): Promise<string>;

  nftContractIsWhitelisted(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  ownerOf(
    tokenId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  pause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  payBackLoan(
    _loanId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renouncePauser(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "safeTransferFrom(address,address,uint256)"(
    from: PromiseOrValue<string>,
    to: PromiseOrValue<string>,
    tokenId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "safeTransferFrom(address,address,uint256,bytes)"(
    from: PromiseOrValue<string>,
    to: PromiseOrValue<string>,
    tokenId: PromiseOrValue<BigNumberish>,
    _data: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setApprovalForAll(
    to: PromiseOrValue<string>,
    approved: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  symbol(overrides?: CallOverrides): Promise<string>;

  totalActiveLoans(overrides?: CallOverrides): Promise<BigNumber>;

  totalNumLoans(overrides?: CallOverrides): Promise<BigNumber>;

  transferFrom(
    from: PromiseOrValue<string>,
    to: PromiseOrValue<string>,
    tokenId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  unpause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateAdminFee(
    _newAdminFeeInBasisPoints: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateMaximumLoanDuration(
    _newMaximumLoanDuration: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateMaximumNumberOfActiveLoans(
    _newMaximumNumberOfActiveLoans: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  whitelistERC20Currency(
    _erc20Currency: PromiseOrValue<string>,
    _setAsWhitelisted: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  whitelistNFTContract(
    _nftContract: PromiseOrValue<string>,
    _setAsWhitelisted: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addPauser(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    adminFeeInBasisPoints(overrides?: CallOverrides): Promise<BigNumber>;

    approve(
      to: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    balanceOf(
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    beginLoan(
      _loanPrincipalAmount: PromiseOrValue<BigNumberish>,
      _maximumRepaymentAmount: PromiseOrValue<BigNumberish>,
      _nftCollateralId: PromiseOrValue<BigNumberish>,
      _loanDuration: PromiseOrValue<BigNumberish>,
      _loanInterestRateForDurationInBasisPoints: PromiseOrValue<BigNumberish>,
      _adminFeeInBasisPoints: PromiseOrValue<BigNumberish>,
      _borrowerAndLenderNonces: [
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>
      ],
      _nftCollateralContract: PromiseOrValue<string>,
      _loanERC20Denomination: PromiseOrValue<string>,
      _lender: PromiseOrValue<string>,
      _borrowerSignature: PromiseOrValue<BytesLike>,
      _lenderSignature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    cancelLoanCommitmentBeforeLoanHasBegun(
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    erc20CurrencyIsWhitelisted(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getApproved(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getChainID(overrides?: CallOverrides): Promise<BigNumber>;

    getPayoffAmount(
      _loanId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getWhetherNonceHasBeenUsedForUser(
      _user: PromiseOrValue<string>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isApprovedForAll(
      owner: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isOwner(overrides?: CallOverrides): Promise<boolean>;

    isPauser(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isValidBorrowerSignature(
      _nftCollateralId: PromiseOrValue<BigNumberish>,
      _borrowerNonce: PromiseOrValue<BigNumberish>,
      _nftCollateralContract: PromiseOrValue<string>,
      _borrower: PromiseOrValue<string>,
      _borrowerSignature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isValidLenderSignature(
      _loanPrincipalAmount: PromiseOrValue<BigNumberish>,
      _maximumRepaymentAmount: PromiseOrValue<BigNumberish>,
      _nftCollateralId: PromiseOrValue<BigNumberish>,
      _loanDuration: PromiseOrValue<BigNumberish>,
      _loanInterestRateForDurationInBasisPoints: PromiseOrValue<BigNumberish>,
      _adminFeeInBasisPoints: PromiseOrValue<BigNumberish>,
      _lenderNonce: PromiseOrValue<BigNumberish>,
      _nftCollateralContract: PromiseOrValue<string>,
      _loanERC20Denomination: PromiseOrValue<string>,
      _lender: PromiseOrValue<string>,
      _interestIsProRated: PromiseOrValue<boolean>,
      _lenderSignature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    liquidateOverdueLoan(
      _loanId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    loanIdToLoan(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        number,
        number,
        number,
        string,
        string,
        string,
        boolean
      ] & {
        loanId: BigNumber;
        loanPrincipalAmount: BigNumber;
        maximumRepaymentAmount: BigNumber;
        nftCollateralId: BigNumber;
        loanStartTime: BigNumber;
        loanDuration: number;
        loanInterestRateForDurationInBasisPoints: number;
        loanAdminFeeInBasisPoints: number;
        nftCollateralContract: string;
        loanERC20Denomination: string;
        borrower: string;
        interestIsProRated: boolean;
      }
    >;

    loanRepaidOrLiquidated(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    maximumLoanDuration(overrides?: CallOverrides): Promise<BigNumber>;

    maximumNumberOfActiveLoans(overrides?: CallOverrides): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<string>;

    nftContractIsWhitelisted(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    ownerOf(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    pause(overrides?: CallOverrides): Promise<void>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    payBackLoan(
      _loanId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    renouncePauser(overrides?: CallOverrides): Promise<void>;

    "safeTransferFrom(address,address,uint256)"(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    "safeTransferFrom(address,address,uint256,bytes)"(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      _data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    setApprovalForAll(
      to: PromiseOrValue<string>,
      approved: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    symbol(overrides?: CallOverrides): Promise<string>;

    totalActiveLoans(overrides?: CallOverrides): Promise<BigNumber>;

    totalNumLoans(overrides?: CallOverrides): Promise<BigNumber>;

    transferFrom(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    unpause(overrides?: CallOverrides): Promise<void>;

    updateAdminFee(
      _newAdminFeeInBasisPoints: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateMaximumLoanDuration(
      _newMaximumLoanDuration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateMaximumNumberOfActiveLoans(
      _newMaximumNumberOfActiveLoans: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    whitelistERC20Currency(
      _erc20Currency: PromiseOrValue<string>,
      _setAsWhitelisted: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    whitelistNFTContract(
      _nftContract: PromiseOrValue<string>,
      _setAsWhitelisted: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AdminFeeUpdated(uint256)"(newAdminFee?: null): AdminFeeUpdatedEventFilter;
    AdminFeeUpdated(newAdminFee?: null): AdminFeeUpdatedEventFilter;

    "Approval(address,address,uint256)"(
      owner?: PromiseOrValue<string> | null,
      approved?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null
    ): ApprovalEventFilter;
    Approval(
      owner?: PromiseOrValue<string> | null,
      approved?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null
    ): ApprovalEventFilter;

    "ApprovalForAll(address,address,bool)"(
      owner?: PromiseOrValue<string> | null,
      operator?: PromiseOrValue<string> | null,
      approved?: null
    ): ApprovalForAllEventFilter;
    ApprovalForAll(
      owner?: PromiseOrValue<string> | null,
      operator?: PromiseOrValue<string> | null,
      approved?: null
    ): ApprovalForAllEventFilter;

    "LoanLiquidated(uint256,address,address,uint256,uint256,uint256,uint256,address)"(
      loanId?: null,
      borrower?: null,
      lender?: null,
      loanPrincipalAmount?: null,
      nftCollateralId?: null,
      loanMaturityDate?: null,
      loanLiquidationDate?: null,
      nftCollateralContract?: null
    ): LoanLiquidatedEventFilter;
    LoanLiquidated(
      loanId?: null,
      borrower?: null,
      lender?: null,
      loanPrincipalAmount?: null,
      nftCollateralId?: null,
      loanMaturityDate?: null,
      loanLiquidationDate?: null,
      nftCollateralContract?: null
    ): LoanLiquidatedEventFilter;

    "LoanRepaid(uint256,address,address,uint256,uint256,uint256,uint256,address,address)"(
      loanId?: null,
      borrower?: null,
      lender?: null,
      loanPrincipalAmount?: null,
      nftCollateralId?: null,
      amountPaidToLender?: null,
      adminFee?: null,
      nftCollateralContract?: null,
      loanERC20Denomination?: null
    ): LoanRepaidEventFilter;
    LoanRepaid(
      loanId?: null,
      borrower?: null,
      lender?: null,
      loanPrincipalAmount?: null,
      nftCollateralId?: null,
      amountPaidToLender?: null,
      adminFee?: null,
      nftCollateralContract?: null,
      loanERC20Denomination?: null
    ): LoanRepaidEventFilter;

    "LoanStarted(uint256,address,address,uint256,uint256,uint256,uint256,uint256,uint256,address,address,bool)"(
      loanId?: null,
      borrower?: null,
      lender?: null,
      loanPrincipalAmount?: null,
      maximumRepaymentAmount?: null,
      nftCollateralId?: null,
      loanStartTime?: null,
      loanDuration?: null,
      loanInterestRateForDurationInBasisPoints?: null,
      nftCollateralContract?: null,
      loanERC20Denomination?: null,
      interestIsProRated?: null
    ): LoanStartedEventFilter;
    LoanStarted(
      loanId?: null,
      borrower?: null,
      lender?: null,
      loanPrincipalAmount?: null,
      maximumRepaymentAmount?: null,
      nftCollateralId?: null,
      loanStartTime?: null,
      loanDuration?: null,
      loanInterestRateForDurationInBasisPoints?: null,
      nftCollateralContract?: null,
      loanERC20Denomination?: null,
      interestIsProRated?: null
    ): LoanStartedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: null,
      newOwner?: null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: null,
      newOwner?: null
    ): OwnershipTransferredEventFilter;

    "Paused(address)"(account?: null): PausedEventFilter;
    Paused(account?: null): PausedEventFilter;

    "PauserAdded(address)"(
      account?: PromiseOrValue<string> | null
    ): PauserAddedEventFilter;
    PauserAdded(
      account?: PromiseOrValue<string> | null
    ): PauserAddedEventFilter;

    "PauserRemoved(address)"(
      account?: PromiseOrValue<string> | null
    ): PauserRemovedEventFilter;
    PauserRemoved(
      account?: PromiseOrValue<string> | null
    ): PauserRemovedEventFilter;

    "Transfer(address,address,uint256)"(
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null
    ): TransferEventFilter;
    Transfer(
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      tokenId?: PromiseOrValue<BigNumberish> | null
    ): TransferEventFilter;

    "Unpaused(address)"(account?: null): UnpausedEventFilter;
    Unpaused(account?: null): UnpausedEventFilter;
  };

  estimateGas: {
    addPauser(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    adminFeeInBasisPoints(overrides?: CallOverrides): Promise<BigNumber>;

    approve(
      to: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    balanceOf(
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    beginLoan(
      _loanPrincipalAmount: PromiseOrValue<BigNumberish>,
      _maximumRepaymentAmount: PromiseOrValue<BigNumberish>,
      _nftCollateralId: PromiseOrValue<BigNumberish>,
      _loanDuration: PromiseOrValue<BigNumberish>,
      _loanInterestRateForDurationInBasisPoints: PromiseOrValue<BigNumberish>,
      _adminFeeInBasisPoints: PromiseOrValue<BigNumberish>,
      _borrowerAndLenderNonces: [
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>
      ],
      _nftCollateralContract: PromiseOrValue<string>,
      _loanERC20Denomination: PromiseOrValue<string>,
      _lender: PromiseOrValue<string>,
      _borrowerSignature: PromiseOrValue<BytesLike>,
      _lenderSignature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    cancelLoanCommitmentBeforeLoanHasBegun(
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    erc20CurrencyIsWhitelisted(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getApproved(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getChainID(overrides?: CallOverrides): Promise<BigNumber>;

    getPayoffAmount(
      _loanId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getWhetherNonceHasBeenUsedForUser(
      _user: PromiseOrValue<string>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isApprovedForAll(
      owner: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isOwner(overrides?: CallOverrides): Promise<BigNumber>;

    isPauser(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isValidBorrowerSignature(
      _nftCollateralId: PromiseOrValue<BigNumberish>,
      _borrowerNonce: PromiseOrValue<BigNumberish>,
      _nftCollateralContract: PromiseOrValue<string>,
      _borrower: PromiseOrValue<string>,
      _borrowerSignature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isValidLenderSignature(
      _loanPrincipalAmount: PromiseOrValue<BigNumberish>,
      _maximumRepaymentAmount: PromiseOrValue<BigNumberish>,
      _nftCollateralId: PromiseOrValue<BigNumberish>,
      _loanDuration: PromiseOrValue<BigNumberish>,
      _loanInterestRateForDurationInBasisPoints: PromiseOrValue<BigNumberish>,
      _adminFeeInBasisPoints: PromiseOrValue<BigNumberish>,
      _lenderNonce: PromiseOrValue<BigNumberish>,
      _nftCollateralContract: PromiseOrValue<string>,
      _loanERC20Denomination: PromiseOrValue<string>,
      _lender: PromiseOrValue<string>,
      _interestIsProRated: PromiseOrValue<boolean>,
      _lenderSignature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    liquidateOverdueLoan(
      _loanId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    loanIdToLoan(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    loanRepaidOrLiquidated(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    maximumLoanDuration(overrides?: CallOverrides): Promise<BigNumber>;

    maximumNumberOfActiveLoans(overrides?: CallOverrides): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    nftContractIsWhitelisted(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    ownerOf(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    payBackLoan(
      _loanId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renouncePauser(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "safeTransferFrom(address,address,uint256)"(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "safeTransferFrom(address,address,uint256,bytes)"(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      _data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setApprovalForAll(
      to: PromiseOrValue<string>,
      approved: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    symbol(overrides?: CallOverrides): Promise<BigNumber>;

    totalActiveLoans(overrides?: CallOverrides): Promise<BigNumber>;

    totalNumLoans(overrides?: CallOverrides): Promise<BigNumber>;

    transferFrom(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateAdminFee(
      _newAdminFeeInBasisPoints: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateMaximumLoanDuration(
      _newMaximumLoanDuration: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateMaximumNumberOfActiveLoans(
      _newMaximumNumberOfActiveLoans: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    whitelistERC20Currency(
      _erc20Currency: PromiseOrValue<string>,
      _setAsWhitelisted: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    whitelistNFTContract(
      _nftContract: PromiseOrValue<string>,
      _setAsWhitelisted: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addPauser(
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    adminFeeInBasisPoints(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    approve(
      to: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    balanceOf(
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    beginLoan(
      _loanPrincipalAmount: PromiseOrValue<BigNumberish>,
      _maximumRepaymentAmount: PromiseOrValue<BigNumberish>,
      _nftCollateralId: PromiseOrValue<BigNumberish>,
      _loanDuration: PromiseOrValue<BigNumberish>,
      _loanInterestRateForDurationInBasisPoints: PromiseOrValue<BigNumberish>,
      _adminFeeInBasisPoints: PromiseOrValue<BigNumberish>,
      _borrowerAndLenderNonces: [
        PromiseOrValue<BigNumberish>,
        PromiseOrValue<BigNumberish>
      ],
      _nftCollateralContract: PromiseOrValue<string>,
      _loanERC20Denomination: PromiseOrValue<string>,
      _lender: PromiseOrValue<string>,
      _borrowerSignature: PromiseOrValue<BytesLike>,
      _lenderSignature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    cancelLoanCommitmentBeforeLoanHasBegun(
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    erc20CurrencyIsWhitelisted(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getApproved(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getChainID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getPayoffAmount(
      _loanId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getWhetherNonceHasBeenUsedForUser(
      _user: PromiseOrValue<string>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isApprovedForAll(
      owner: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isPauser(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isValidBorrowerSignature(
      _nftCollateralId: PromiseOrValue<BigNumberish>,
      _borrowerNonce: PromiseOrValue<BigNumberish>,
      _nftCollateralContract: PromiseOrValue<string>,
      _borrower: PromiseOrValue<string>,
      _borrowerSignature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isValidLenderSignature(
      _loanPrincipalAmount: PromiseOrValue<BigNumberish>,
      _maximumRepaymentAmount: PromiseOrValue<BigNumberish>,
      _nftCollateralId: PromiseOrValue<BigNumberish>,
      _loanDuration: PromiseOrValue<BigNumberish>,
      _loanInterestRateForDurationInBasisPoints: PromiseOrValue<BigNumberish>,
      _adminFeeInBasisPoints: PromiseOrValue<BigNumberish>,
      _lenderNonce: PromiseOrValue<BigNumberish>,
      _nftCollateralContract: PromiseOrValue<string>,
      _loanERC20Denomination: PromiseOrValue<string>,
      _lender: PromiseOrValue<string>,
      _interestIsProRated: PromiseOrValue<boolean>,
      _lenderSignature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    liquidateOverdueLoan(
      _loanId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    loanIdToLoan(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    loanRepaidOrLiquidated(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    maximumLoanDuration(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    maximumNumberOfActiveLoans(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    nftContractIsWhitelisted(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ownerOf(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    payBackLoan(
      _loanId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renouncePauser(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "safeTransferFrom(address,address,uint256)"(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "safeTransferFrom(address,address,uint256,bytes)"(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      _data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setApprovalForAll(
      to: PromiseOrValue<string>,
      approved: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    symbol(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalActiveLoans(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalNumLoans(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferFrom(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateAdminFee(
      _newAdminFeeInBasisPoints: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateMaximumLoanDuration(
      _newMaximumLoanDuration: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateMaximumNumberOfActiveLoans(
      _newMaximumNumberOfActiveLoans: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    whitelistERC20Currency(
      _erc20Currency: PromiseOrValue<string>,
      _setAsWhitelisted: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    whitelistNFTContract(
      _nftContract: PromiseOrValue<string>,
      _setAsWhitelisted: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
